/*
* generated by Xtext
*/
package org.vclipse.procedure.ui.contentassist;

import org.vclipse.procedure.ui.contentassist.AbstractProcedureProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ProcedureProposalProvider extends AbstractProcedureProposalProvider {

}
