$self.GEN_UI_LAYOUT_NAME = 'Notebook',
$self.UMTS ?= 'F',
$del_default($self, SCREEN_SIZE, $self.SCREEN_SIZE) if
  specified $self.SCREEN_SIZE,
$self.SCREEN_SIZE ?= '17' if $self.NOTEBOOK_TYPE = 'multimedia',
$self.SCREEN_SIZE ?= '15.4' if
  $self.NOTEBOOK_TYPE in ('development', 'business'),
$del_default($self, CORE_AMOUNT, $self.CORE_AMOUNT) if
  specified $self.CORE_AMOUNT,
$self.CORE_AMOUNT ?= 2 if
  $self.NOTEBOOK_TYPE in ('development', 'multimedia', 'business'),
$self.CORE_AMOUNT ?= 1 if $self.NOTEBOOK_TYPE = 'netbook',
$del_default($self, HARD_DISK_SIZE, $self.HARD_DISK_SIZE) if
  specified $self.HARD_DISK_SIZE,
$self.HARD_DISK_SIZE ?= '60' if $self.NOTEBOOK_TYPE = 'netbook',
$self.HARD_DISK_SIZE ?= '120' if
  $self.NOTEBOOK_TYPE in ('development', 'multimedia', 'business'),
$del_default($self, RAM_MODULES_AMOUNT, $self.RAM_MODULES_AMOUNT) if
  specified $self.RAM_MODULES_AMOUNT,
$self.RAM_MODULES_AMOUNT ?= 1 if $self.NOTEBOOK_TYPE in ('netbook'),
$self.RAM_MODULES_AMOUNT ?= 2 if
  $self.NOTEBOOK_TYPE in ('business', 'development'),
$self.RAM_MODULES_AMOUNT ?= 4 if $self.NOTEBOOK_TYPE in ('multimedia'),
$self.WEBCAM ?= 'F',
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if
  $self.NOTEBOOK_TYPE in ('multimedia', 'netbook'),
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000656',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if
  $self.NOTEBOOK_TYPE in ('business', 'development'),
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000657',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if $self.NOTEBOOK_TYPE = 'netbook',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000658',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if $self.NOTEBOOK_TYPE = 'business',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000659',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if $self.UMTS = 'T',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000672',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$del_default($self, DISPLAY, $self.DISPLAY) if specified $self.DISPLAY,
$self.DISPLAY ?= 'non-glare' if $self.SCREEN_SIZE in ('10.1', '12'),
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if
  $self.NOTEBOOK_TYPE in ('business', 'multimedia', 'development') and
  $self.CORE_AMOUNT = 2,
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000660',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if
  $self.NOTEBOOK_TYPE in ('multimedia', 'development') and
  $self.CORE_AMOUNT = 4,
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000661',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if $self.HARD_DISK_SIZE = '60',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000669',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if $self.HARD_DISK_SIZE = '120',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000670',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if $self.HARD_DISK_SIZE = '340',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000671',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 =
$self.RAM_MODULES_AMOUNT  - 8  * FLOOR($self.RAM_MODULES_AMOUNT  / 8),
$self.GEN_AUX_NUM_02 =
$self.GEN_AUX_NUM_01  - 4  * FLOOR($self.GEN_AUX_NUM_01  / 4),
$self.GEN_AUX_NUM_03 =
$self.GEN_AUX_NUM_02  - 2  * FLOOR($self.GEN_AUX_NUM_02  / 2),
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000652',
  GEN_MU_QTY = $self.GEN_AUX_NUM_03,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_03 > 0,
$self.GEN_AUX_NUM_01 =
$self.RAM_MODULES_AMOUNT  - 8  * FLOOR($self.RAM_MODULES_AMOUNT  / 8),
$self.GEN_AUX_NUM_02 =
FLOOR(($self.GEN_AUX_NUM_01  - 4  * FLOOR($self.GEN_AUX_NUM_01  / 4))
       / 2),
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000653',
  GEN_MU_QTY = $self.GEN_AUX_NUM_02,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_02 > 0,
$self.GEN_AUX_NUM_01 =
FLOOR(($self.RAM_MODULES_AMOUNT  -
       8  * FLOOR($self.RAM_MODULES_AMOUNT  / 8))  / 4),
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000654',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = FLOOR($self.RAM_MODULES_AMOUNT  / 8),
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000655',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if $self.WEBCAM = 'T',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000673',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if
  $self.SCREEN_SIZE = '10.1' and $self.DISPLAY = 'glare',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000662',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if
  $self.SCREEN_SIZE = '10.1' and $self.DISPLAY = 'non-glare',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000663',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if
  $self.SCREEN_SIZE = '12' and $self.DISPLAY = 'glare',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000664',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if
  $self.SCREEN_SIZE = '12' and $self.DISPLAY = 'non-glare',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000665',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if
  $self.SCREEN_SIZE = '14' and $self.DISPLAY = 'glare',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000666',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if
  $self.SCREEN_SIZE = '15.4' and $self.DISPLAY = 'glare',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000667',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0,
$self.GEN_AUX_NUM_01 = 0,
$self.GEN_AUX_NUM_01 = 1 if
  $self.SCREEN_SIZE = '17' and $self.DISPLAY = 'glare',
pfunction Z_VC_GEN_SET_VBOM_MU (
  GEN_MU_ID = 'E8300001000668',
  GEN_MU_QTY = $self.GEN_AUX_NUM_01,
  GEN_VBOM_CSTIC = 'GEN_VBOM_CURR'
) if $self.GEN_AUX_NUM_01 > 0.