/*
 * generated by Xtext
 */
package org.vclipse.configscan.vcmlt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VcmlTUiModule extends org.vclipse.configscan.vcmlt.ui.AbstractVcmlTUiModule {
	public VcmlTUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
