/*
* generated by Xtext
*/
package org.vclipse.tests.vcml;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class VCMLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.vclipse.vcml.ui.internal.VCMLActivator.getInstance().getInjector("org.vclipse.vcml.VCML");
	}
	
}
