/*
* generated by Xtext
*/
package org.vclipse.dependency.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.vclipse.vcml.ui.labeling.AbstractVClipseLabelProvider;
import org.vclipse.vcml.vcml.CharacteristicReference_P;
import org.vclipse.vcml.vcml.Function;
import org.vclipse.vcml.vcml.IsInvisible;
import org.vclipse.vcml.vcml.ProcedureLocation;
import org.vclipse.vcml.vcml.Table;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class DependencyLabelProvider extends AbstractVClipseLabelProvider {

	@Inject
	public DependencyLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	public String text(IsInvisible element) {
		return text(element.getCharacteristic()) + "is invisible ";
	}
	
	public String text(Function element) {
		return text(element.getFunction()) + " (...)";
	}

	public String text(Table element) {
		return text(element.getTable()) + " (...)";
	}
	
	public String text(CharacteristicReference_P element) {
		ProcedureLocation location = element.getLocation();
		return (location!=null ? location.getLiteral() + "." : "") + text(element.getCharacteristic());
	}
}
