/*******************************************************************************
 * Copyright (c) 2010 webXcerpt Software GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    webXcerpt Software GmbH - initial creator
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.vclipse.idoc;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.vclipse.idoc.conversion.IDocValueConverter;


/**
 * Use this class to register components to be used within the IDE.
 */
public class IDocRuntimeModule extends org.vclipse.idoc.AbstractIDocRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return IDocValueConverter.class;
	}

}
