/**
 * generated by Xtext
 */
package org.vclipse.idoc.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class IDocProposalProvider /* implements AbstractIDocProposalProvider  */{
}
