/*
 * generated by Xtext
 */
package org.vclipse.idoc.ui.contentassist

import org.vclipse.idoc.ui.contentassist.AbstractIDocProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class IDocProposalProvider extends AbstractIDocProposalProvider {
}
