/**
 * generated by Xtext
 */
package org.vclipse.idoc.validation;

import org.eclipse.xtext.validation.Check;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class IDocValidator /* implements AbstractIDocValidator  */{
  private final static int LENGTH_LIMIT = 72;
  
  @Check
  public void checkSegment(final /* Segment */Object segment) {
    throw new Error("Unresolved compilation problems:"
      + "\nStringField cannot be resolved to a type."
      + "\nThe method name is undefined for the type IDocValidator"
      + "\nThe method error is undefined for the type IDocValidator"
      + "\nIDocPackage$Literals cannot be resolved to a type."
      + "\nStringField cannot be resolved to a type."
      + "\ntype cannot be resolved"
      + "\nfields cannot be resolved"
      + "\nvalue cannot be resolved"
      + "\nlength cannot be resolved"
      + "\n> cannot be resolved"
      + "\nSTRING_FIELD__VALUE cannot be resolved");
  }
}
