/*
 * generated by Xtext
 */
package org.vclipse.condition.ui.contentassist

import org.vclipse.condition.ui.contentassist.AbstractConditionProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class ConditionProposalProvider extends AbstractConditionProposalProvider {
}
