/*
* generated by Xtext
*/
package org.vclipse.tests.condition;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ConditionUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.vclipse.condition.ui.internal.ConditionActivator.getInstance().getInjector("org.vclipse.condition.Condition");
	}
	
}
