/*******************************************************************************
 * Copyright (c) 2010 webXcerpt Software GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    webXcerpt Software GmbH - initial creator
 *******************************************************************************/
/*
* generated by Xtext
*/
package org.vclipse.idoc.labeling;

import org.eclipse.xtext.ui.core.DefaultLabelProvider;

import org.vclipse.idoc.iDoc.IDoc;
import org.vclipse.idoc.iDoc.NumberField;
import org.vclipse.idoc.iDoc.Record;
import org.vclipse.idoc.iDoc.Segment;
import org.vclipse.idoc.iDoc.StringField;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class IDocLabelProvider extends DefaultLabelProvider {
	
	String text(final IDoc element) {
		return element.getName() + " " + element.getType() + " " + element.getMessageType();
	}
	
	String text(final Record element) {
		return element.getType();
	}
	
	String text(final StringField element) {
		return element.getName() + " = \"" + element.getValue() + "\"";
	}
	
	String text(final NumberField element) {
		return element.getName() + " = " + element.getValue();
	}
	
	public String image(final IDoc element) {
		return "idoc.png";
	}

	public String image(final Segment element) {
		return "page_white_text.png";
	}

}
