/**
 * generated by Xtext
 */
package org.vclipse.configscan.vcmlt.ui.contentassist;

import org.vclipse.configscan.vcmlt.ui.contentassist.AbstractVcmlTProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class VcmlTProposalProvider extends AbstractVcmlTProposalProvider {
}
