/*
 * generated by Xtext
 */
package org.vclipse.condition.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.resource.containers.IAllContainersState;
import org.vclipse.vcml.ui.resources.VcmlResourcesStateProvider;

import com.google.inject.Provider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConditionUiModule extends org.vclipse.condition.ui.AbstractConditionUiModule {
	
	public ConditionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Provider<IAllContainersState> provideIAllContainersState() {
		return VcmlResourcesStateProvider.getInstance();
	}
}
