/*
 * generated by Xtext
 */
package org.vclipse.condition.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConditionUiModule extends org.vclipse.condition.ui.AbstractConditionUiModule {
	
	public ConditionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
