/*
 * generated by Xtext
 */
package org.vclipse.constraint.ui.contentassist

import org.vclipse.constraint.ui.contentassist.AbstractConstraintProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class ConstraintProposalProvider extends AbstractConstraintProposalProvider {
}
