/*
* generated by Xtext
*/
package org.vclipse.condition.ui.labeling;

import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.xtext.resource.IReferenceDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class ConditionDescriptionLabelProvider extends DefaultDescriptionLabelProvider {

	@Inject
	private ConditionLabelProvider labelProvider;
	
	@Override
	public Object text(IReferenceDescription referenceDescription) {
		URI sourceUri = referenceDescription.getSourceEObjectUri();
		EObject object = new ResourceSetImpl().getEObject(sourceUri, true);
		return labelProvider.getText(object);
	}
}
