/*
* generated by Xtext
*/
package org.vclipse.condition.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.vclipse.dependency.ui.labeling.DependencyLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class ConditionLabelProvider extends DependencyLabelProvider {

	@Inject
	public ConditionLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
}

