/**
 * generated by Xtext
 */
package org.vclipse.constraint.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ConstraintProposalProvider /* implements AbstractConstraintProposalProvider  */{
}
