/*
 * generated by Xtext
 */
package org.vclipse.constraint.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.resource.containers.IAllContainersState;
import org.vclipse.vcml.ui.editor.VcmlResourceContainerState;

import com.google.inject.Provider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConstraintUiModule extends org.vclipse.constraint.ui.AbstractConstraintUiModule {
	
	public ConstraintUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Provider<IAllContainersState> provideIAllContainersState() {
		return org.eclipse.xtext.ui.shared.Access.<IAllContainersState>provider(VcmlResourceContainerState.class);
	}
}
