/*
 * generated by Xtext
 */
package org.vclipse.constraint.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConstraintUiModule extends org.vclipse.constraint.ui.AbstractConstraintUiModule {
	
	public ConstraintUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
