/*
 * generated by Xtext
 */
package org.vclipse.condition.formatting;

import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.vclipse.dependency.formatting.DependencyFormatter;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class ConditionFormatter extends DependencyFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig config) {
		
	}
}
