/*
* generated by Xtext
*/
package org.vclipse.dependency.ui.outline;

import org.eclipse.jface.preference.IPreferenceStore;
import org.vclipse.vcml.ui.outline.VCMLOutlineTreeProvider;

import com.google.inject.Inject;

/**
 * customization of the default outline structure
 * 
 */
public class DependencyOutlineTreeProvider extends VCMLOutlineTreeProvider {

	@Inject
	public DependencyOutlineTreeProvider(IPreferenceStore preferenceStore) {
		super(preferenceStore);
	}
}

