/**
 * generated by Xtext
 */
package org.vclipse.dependency.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DependencyProposalProvider /* implements AbstractDependencyProposalProvider  */{
}
