/*
* generated by Xtext
*/
package org.vclipse.tests.idoc;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class IDocUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.vclipse.idoc.ui.internal.IDocActivator.getInstance().getInjector("org.vclipse.idoc.IDoc");
	}
	
}
