/*
* generated by Xtext
*/
package org.vclipse.tests.vcmlt;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class VcmlTUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.vclipse.configscan.vcmlt.ui.internal.VcmlTActivator.getInstance().getInjector("org.vclipse.configscan.vcmlt.VcmlT");
	}
	
}
