/*******************************************************************************
 * Copyright (c) 2010 webXcerpt Software GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *    webXcerpt Software GmbH - initial creator
 ******************************************************************************/
/*
 * generated by Xtext
 */
package org.vclipse.vcml.ui;

import java.io.PrintStream;

import org.eclipse.core.resources.IWorkspaceRoot;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.ui.views.contentoutline.IContentOutlinePage;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.documentation.impl.MultiLineCommentDocumentationProvider;
import org.eclipse.xtext.resource.containers.IAllContainersState;
import org.eclipse.xtext.ui.IImageHelper;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.hyperlinking.HyperlinkLabelProvider;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;
import org.eclipse.xtext.ui.editor.outline.IOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.templates.XtextTemplateContextType;
import org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringExecuter;
import org.eclipse.xtext.ui.shared.Access;
import org.vclipse.base.ui.util.ClasspathAwareImageHelper;
import org.vclipse.base.ui.util.IExtendedImageHelper;
import org.vclipse.refactoring.IPreviewEObjectComputer;
import org.vclipse.refactoring.IRefactoringConfiguration;
import org.vclipse.refactoring.IRefactoringExecuter;
import org.vclipse.refactoring.IRefactoringUIConfiguration;
import org.vclipse.vcml.refactoring.VCMLCustomisation;
import org.vclipse.vcml.refactoring.VCMLRefactoring;
import org.vclipse.vcml.ui.editor.hover.VCMLHoverProvider;
import org.vclipse.vcml.ui.hyperlinks.VcmlHyperlinkHelper;
import org.vclipse.vcml.ui.hyperlinks.VcmlHyperlinkLabelProvider;
import org.vclipse.vcml.ui.outline.VCMLOutlinePage;
import org.vclipse.vcml.ui.outline.VCMLOutlineTreeProvider;
import org.vclipse.vcml.ui.refactoring.PreviewEntityComputer;
import org.vclipse.vcml.ui.refactoring.VCMLUICustomisation;
import org.vclipse.vcml.ui.refactoring.VcmlRenameRefactoringExecutor;
import org.vclipse.vcml.ui.resources.VcmlResourcesStateProvider;
import org.vclipse.vcml.ui.syntaxcoloring.VCMLAntlrTokenToAttributeIdMapper;
import org.vclipse.vcml.ui.templates.VcmlTemplateContextType;

import com.google.inject.Provider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VCMLUiModule extends org.vclipse.vcml.ui.AbstractVCMLUiModule {
	
	public VCMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends IContentOutlinePage> bindIContentOutlinePage() {
		return VCMLOutlinePage.class;
	}

	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
		return VCMLHoverProvider.class;
	}

	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProvider() {
		return MultiLineCommentDocumentationProvider.class;
	}
	
	public PrintStream bindPrintStream() {
		return System.out;
	}
	
	public IWorkspaceRoot bindWorkspaceRoot() {
		return ResourcesPlugin.getWorkspace().getRoot();
	}
	
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return VCMLAntlrTokenToAttributeIdMapper.class;
	}

	public Provider<IAllContainersState> provideIAllContainersState() {
		return VcmlResourcesStateProvider.getInstance();
	}

	@Override
	public Class<? extends IImageHelper> bindIImageHelper() {
		return ClasspathAwareImageHelper.class;
	}

	@Override
	public Class<? extends IOutlineTreeProvider> bindIOutlineTreeProvider() {
		return VCMLOutlineTreeProvider.class;
	}
	
	public Class<? extends XtextTemplateContextType> bindXtextTemplateContextType() {
		return VcmlTemplateContextType.class;
	}
	
	public Class<? extends IExtendedImageHelper> bindIExtendedImageHelper() {
		return ClasspathAwareImageHelper.class;
	}
	
	/**
	 * Extension of the re-name re-factoring
	 */
	public Provider<? extends RenameRefactoringExecuter> provideRenameRefactoringExecuter() {
		return Access.provider(VcmlRenameRefactoringExecutor.class);
	}
	
	/**
	 * VCML Re-factoring
	 */
	public Class<? extends IPreviewEObjectComputer> bindRelevantEntityComputer() {
		return PreviewEntityComputer.class;
	}
	
	public Class<? extends IRefactoringConfiguration> bindRefactoringConfiguration() {
		return VCMLCustomisation.class;
	}
	
	public Class<? extends IRefactoringUIConfiguration> bindRefactoringUIConfiguration() {
		return VCMLUICustomisation.class;
	}
	
	public Class<? extends IRefactoringExecuter> bindRefactoringExecuter() {
		return VCMLRefactoring.class;
	}
	
	/**
	 * Hyperlinks
	 */
	public void configureHyperlinkLabelProvider(com.google.inject.Binder binder) {
		binder.bind(ILabelProvider.class).annotatedWith(HyperlinkLabelProvider.class).to(VcmlHyperlinkLabelProvider.class);
	}
	
	public Class<? extends IHyperlinkHelper> bindIHyperlinkHelper() {
		return VcmlHyperlinkHelper.class;
	}
}
