/*******************************************************************************
 * Copyright (c) 2010 webXcerpt Software GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    webXcerpt Software GmbH - initial creator
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.vclipse.vcml;

import java.io.PrintStream;

import org.eclipse.jface.text.IInformationControlCreator;
import org.eclipse.jface.text.ITextHover;
import org.eclipse.ui.views.contentoutline.IContentOutlinePage;
import org.eclipse.xtext.ui.common.editor.syntaxcoloring.antlr.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.core.editor.FastLineBasedDamagerRepairer;
import org.eclipse.xtext.ui.core.editor.IDamagerRepairer;
import org.eclipse.xtext.ui.core.editor.XtextSourceViewerConfiguration;
import org.eclipse.xtext.ui.core.editor.contentassist.ContentAssistContext.Factory;
import org.vclipse.vcml.editor.VCMLInformationControlCreator;
import org.vclipse.vcml.editor.VCMLSourceViewerConfiguration;
import org.vclipse.vcml.editor.VCMLTextHover;
import org.vclipse.vcml.outline.VCMLOutlinePage;
import org.vclipse.vcml.syntaxcoloring.VCMLAntlrTokenToAttributeIdMapper;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VCMLUiModule extends org.vclipse.vcml.AbstractVCMLUiModule {

	/**
	 * @see org.vclipse.vcml.AbstractVCMLUiModule#bindIContentOutlinePage()
	 */
	@Override
	public Class<? extends IContentOutlinePage> bindIContentOutlinePage() {
		return VCMLOutlinePage.class;
	}

	public Class<? extends XtextSourceViewerConfiguration> bindSourceViewerConfiguration() {
		return VCMLSourceViewerConfiguration.class;
	}

	public Class<? extends ITextHover> bindTextHover() {
		return VCMLTextHover.class;
	}
	
	public Class<? extends IInformationControlCreator> bindInformationControlCreator() {
		return VCMLInformationControlCreator.class;
	}
	
	/**
	 * @return
	 */
	public PrintStream bindPrintStream() {
		return System.out;
	}
	
	/**
	 * @return
	 */
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return VCMLAntlrTokenToAttributeIdMapper.class;
	}

	@Override
	public Class<? extends IDamagerRepairer> bindIDamagerRepairer() {
		return FastLineBasedDamagerRepairer.class;
	}

	@Override
	public Class<? extends Factory> bindContentAssistContext$Factory() {
		return org.vclipse.vcml.contentassist.ParserBasedContentAssistContextFactory.class;
	}

	
	
}
