/**
 * generated by Xtext
 */
package org.vclipse.condition.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ConditionProposalProvider /* implements AbstractConditionProposalProvider  */{
}
