/*
* generated by Xtext
*/
package org.vclipse.tests.dependency;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DependencyUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.vclipse.dependency.ui.internal.DependencyActivator.getInstance().getInjector("org.vclipse.dependency.Dependency");
	}
	
}
