/*
 * generated by Xtext
 */
package org.vclipse.configscan.vcmlt;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VcmlTRuntimeModule extends org.vclipse.configscan.vcmlt.AbstractVcmlTRuntimeModule {

}
